
spring:
  datasource:
    driverClassName: &dbDriver org.postgresql.Driver
    url: &dbUrl jdbc:postgresql://localhost:5432/postgres
    username: &dbUsername postgres
    password: &dbPassword 11
  jpa:
    show-sql: true
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        format_sql: true
        connection:
          driver_class: *dbDriver
          url: *dbUrl
          username: *dbUsername
          password: *dbPassword
          release_mode: after_transaction
        c3p0:
          min_size: 5
          max_size: 20
          timeout: 300
          max_statements: 50
          idle_test_period: 3000
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
        current_session_context_class: thread

logging:
  level.: DEBUG
  level.org.hibernate: INFO
  level.org.springframework: INFO
  level.org.apache.cxf: INFO
  level.com.mchange: 'OFF'